  deploy:
    runs-on: self-hosted
    needs: build

    steps:
      - name: Pull Docker image
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/cicd-demo:${{ github.sha }} || docker pull ${{ secrets.DOCKER_USERNAME }}/cicd-demo:latest

      - name: Stop old container
        run: |
          docker stop cicd-demo || true
          docker rm cicd-demo || true

      - name: Run new container (STRICT)
        run: |
          set -e

          docker pull ${{ secrets.DOCKER_USERNAME }}/cicd-demo:latest

          docker stop cicd-demo || true
          docker rm cicd-demo || true

          docker run -d \
            -p 3000:80 \
            --name cicd-demo \
            --restart unless-stopped \
            ${{ secrets.DOCKER_USERNAME }}/cicd-demo:latest

          echo "=== VERIFY ==="
          docker ps -a

      - name: Debug
        run: |
          echo "=== Containers ==="
          docker ps -a
          echo "=== Images ==="
          docker images
