name: sonarBuild

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build, test, and analyze
    runs-on: [self-hosted, macOS]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - run: npm install
      - run: npm test -- --coverage --watchAll=false

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
